# Generated by Django 4.2.3 on 2023-08-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_by',
        ),
    ]
