# Generated by Django 4.2.3 on 2023-08-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
