# Generated by Django 4.2.3 on 2023-08-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_alter_cinemahall_size_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='hall_reservation_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
