# Generated by Django 4.2.3 on 2023-07-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('halls', '0002_remove_moviesession_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм'),
            preserve_default=False,
        ),
    ]
