# Generated by Django 4.2.3 on 2023-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_moviesession_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
