# Generated by Django 4.2.3 on 2023-08-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_moviesession_hall_reservation_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='reserved_seats',
        ),
    ]
