# Generated by Django 4.2.3 on 2023-07-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_price'),
        ('halls', '0004_alter_moviesession_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='poster',
            field=models.ImageField(default=2, upload_to='posters/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фільм'),
        ),
    ]
