# Generated by Django 4.2.3 on 2023-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
