# Generated by Django 4.2.3 on 2023-07-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0007_alter_cinemahall_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
