# Generated by Django 4.2.3 on 2023-07-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_price'),
        ('halls', '0008_remove_moviesession_total_seats_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='booked_seats',
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
